on:
  push:
    branches:
      - master
name: Deploy to Heroku
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Python 
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests 
      run: |
        coverage run -m nose2 --coverage coverage
    - name: Login to Heroku Container registry
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku container:login
    - uses: akhileshns/heroku-deploy@v3.0.0
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: "espoir.mur@gmail.com"
        branch: "HEAD" 
        dontuseforce: false 
        usedocker: false 
